'use client'
import * as React from 'react'
import { ChevronDown, ChevronRight, RotateCcw, Search, Sliders } from 'lucide-react'
import { getComponentCodeDefinition } from '@/features/components/componentTemplateRegistry'
import { useCanvasEngineStore } from '@/stores/canvasEngineStore'
import { useInspectorStore } from '@/stores/inspectorStore'
import type { CanvasNode } from '@/types/canvas-engine.types'

const common = [{ name: 'width', type: 'number' }, { name: 'height', type: 'number' }, { name: 'background', type: 'string' }, { name: 'borderRadius', type: 'number' }, { name: 'padding', type: 'number' }, { name: 'opacity', type: 'number' }, { name: 'visible', type: 'boolean' }, { name: 'locked', type: 'boolean' }] as const
export function DynamicPropertyInspector() {
  const nodes = useCanvasEngineStore((state) => state.nodes); const query = useInspectorStore((state) => state.query); const setQuery = useInspectorStore((state) => state.setQuery); const selected = nodes.filter((node) => node.selected)
  const update = (name: string, value: unknown) => selected.forEach((node) => { const patch = buildPatch(node, name, value); window.dispatchEvent(new CustomEvent('canvas-node-update', { detail: { id: node.id, patch } })) })
  if (!selected.length) return <div className="flex h-full flex-col"><Header query={query} setQuery={setQuery}/><div className="p-4 text-xs text-[#8e9192]"><Sliders className="mb-3 h-6 w-6 text-[#444748]"/><p className="font-medium text-[#c4c7c8]">Canvas</p><p className="mt-1">Select a component to edit its properties.</p><div className="mt-5 space-y-2 border-t border-[#1c1b1b] pt-3"><p>Zoom: 100%</p><p>Grid: enabled</p><p>Snap: disabled</p></div></div></div>
  const definition = selected.length === 1 ? getComponentCodeDefinition(selected[0].type) : null
  const properties = [...(definition?.properties ?? []), ...common].filter((property, index, values) => values.findIndex((item) => item.name === property.name) === index && property.name.toLowerCase().includes(query.toLowerCase()))
  const reset = () => selected.forEach((node) => window.dispatchEvent(new CustomEvent('canvas-node-update', { detail: { id: node.id, patch: { data: { ...node.data, properties: {} } } } })))
  return <div className="flex h-full flex-col"><Header query={query} setQuery={setQuery}/><div className="border-b border-[#1c1b1b] px-3 py-2 text-xs text-[#8e9192]">{selected.length > 1 ? `${selected.length} components selected` : definition?.name ?? selected[0].type}</div><div className="flex-1 overflow-y-auto p-3"><Section title="Properties">{properties.map((property) => <PropertyControl key={property.name} name={property.name} type={property.type} node={selected[0]} multi={selected.length > 1} onChange={update}/>)}</Section><Section title="Actions"><button onClick={reset} className="flex items-center gap-2 text-xs text-[#8e9192] hover:text-white"><RotateCcw className="h-3.5 w-3.5"/>Reset component properties</button></Section></div></div>
}
function Header({ query, setQuery }: { query: string; setQuery: (query: string) => void }) { return <><div className="flex h-10 items-center px-3 text-xs font-semibold uppercase tracking-wider text-[#c4c7c8]">Properties</div><label className="mx-3 mb-2 flex items-center gap-2 rounded border border-[#353434] bg-[#101010] px-2"><Search className="h-3 w-3 text-[#777]"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search properties" className="h-7 min-w-0 flex-1 bg-transparent text-xs outline-none"/></label></> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { const expanded = useInspectorStore((state) => state.expanded[title] !== false); const toggle = useInspectorStore((state) => state.toggle); return <section className="mb-4 border-b border-[#1c1b1b] pb-3"><button onClick={() => toggle(title)} className="mb-2 flex w-full items-center gap-1 text-[10px] font-semibold uppercase tracking-wider text-[#8e9192]">{expanded ? <ChevronDown className="h-3 w-3"/> : <ChevronRight className="h-3 w-3"/>}{title}</button>{expanded && <div className="space-y-2">{children}</div>}</section> }
function PropertyControl({ name, type, node, multi, onChange }: { name: string; type: string; node: CanvasNode; multi: boolean; onChange: (name: string, value: unknown) => void }) { const value = readValue(node, name); const boolean = type === 'boolean'; return <label className="flex items-center justify-between gap-2 text-xs text-[#8e9192]"><span className="capitalize">{name.replace(/([A-Z])/g, ' $1')}</span>{boolean ? <input type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(name, event.target.checked)}/> : <input type={type === 'number' ? 'number' : 'text'} value={multi ? '' : String(value ?? '')} placeholder={multi ? 'Mixed' : ''} onChange={(event) => onChange(name, type === 'number' ? Number(event.target.value) : event.target.value)} className="h-7 w-28 rounded border border-[#353434] bg-[#101010] px-2 text-xs text-white outline-none focus:border-blue-500"/>}</label> }
function readValue(node: CanvasNode, name: string) { if (name === 'width') return node.data.width; if (name === 'height') return node.data.height; if (name === 'locked') return node.data.locked; if (name === 'visible') return node.data.visible !== false; if (name === 'text') return node.data.label; return node.data.properties[name] }
function buildPatch(node: CanvasNode, name: string, value: unknown) { if (name === 'width' || name === 'height') return { data: { ...node.data, [name]: value }, style: { ...node.style, [name]: value } }; if (name === 'locked') return { data: { ...node.data, locked: Boolean(value) } }; if (name === 'visible') return { hidden: !value, data: { ...node.data, visible: Boolean(value) } }; if (name === 'text') return { data: { ...node.data, label: String(value) } }; return { data: { ...node.data, properties: { ...node.data.properties, [name]: value } } } }
