'use client'
import * as React from 'react'
import { Laptop, RefreshCw, Smartphone, Tablet } from 'lucide-react'
import { getComponent } from '@/features/components/componentRegistry'
import { useCanvasEngineStore } from '@/stores/canvasEngineStore'
import { usePreviewStore, type PreviewDevice } from '@/stores/previewStore'
import type { CanvasNode } from '@/types/canvas-engine.types'

const widths: Record<PreviewDevice, number> = { desktop: 960, tablet: 720, mobile: 390 }
function PreviewNode({ node }: { node: CanvasNode }) { const definition = getComponent(node.type); const properties = node.data.properties; const style: React.CSSProperties = { position: 'absolute', left: node.position.x, top: node.position.y, width: node.data.width, height: node.data.height, opacity: Number(properties.opacity ?? 1), padding: Number(properties.padding ?? 0), borderRadius: Number(properties.borderRadius ?? 4), background: String(properties.background ?? 'transparent') }; const label = node.data.label; if (node.hidden || node.data.visible === false) return null; const body = node.type === 'input' ? <input disabled placeholder={String(properties.placeholder ?? label)} className="h-full w-full rounded border px-2"/> : node.type === 'textarea' ? <textarea disabled placeholder={String(properties.placeholder ?? label)} className="h-full w-full rounded border p-2"/> : node.type === 'image' ? <img alt={String(properties.alt ?? label)} src={String(properties.src ?? 'https://placehold.co/400x300?text=Image')} className="h-full w-full rounded object-cover"/> : node.type === 'button' ? <button className="h-full w-full rounded bg-blue-600 text-white">{label}</button> : node.type === 'heading' ? <h2 className="text-2xl font-bold">{label}</h2> : node.type === 'progress' ? <div className="h-full w-full rounded bg-slate-200"><div className="h-full w-2/3 rounded bg-blue-600"/></div> : node.type === 'spinner' ? <div className="h-8 w-8 animate-spin rounded-full border-2 border-blue-600 border-t-transparent"/> : <div className="h-full w-full rounded border border-slate-200 bg-white p-2 text-sm text-slate-800">{label}</div>; return <div style={style} title={definition?.description}>{body}</div> }
export function LivePreviewPanel() { const nodes = useCanvasEngineStore((state) => state.nodes); const device = usePreviewStore((state) => state.device); const setDevice = usePreviewStore((state) => state.setDevice); const zoom = usePreviewStore((state) => state.zoom); const setZoom = usePreviewStore((state) => state.setZoom); const [key, refresh] = React.useState(0); return <section className="flex min-w-0 flex-1 flex-col border-l border-[#1c1b1b] bg-[#101010]"><header className="flex h-10 items-center gap-1 border-b border-[#1c1b1b] px-2"><span className="mr-2 text-xs font-semibold uppercase tracking-wider text-[#c4c7c8]">Preview</span>{([['desktop', Laptop], ['tablet', Tablet], ['mobile', Smartphone]] as const).map(([value, Icon]) => <button key={value} onClick={() => setDevice(value)} className={`rounded p-1.5 ${device === value ? 'bg-blue-600 text-white' : 'text-[#8e9192] hover:bg-[#201f1f]'}`} title={value}><Icon className="h-3.5 w-3.5"/></button>)}<div className="flex-1"/><button onClick={() => setZoom(1)} className="px-1.5 text-xs text-[#8e9192]">{Math.round(zoom * 100)}%</button><button onClick={() => refresh((value) => value + 1)} title="Refresh preview" className="p-1.5 text-[#8e9192]"><RefreshCw className="h-3.5 w-3.5"/></button></header><div className="flex-1 overflow-auto bg-[#191919] p-5"><div key={key} className="relative mx-auto min-h-[640px] origin-top bg-white shadow-2xl transition-all" style={{ width: widths[device], transform: `scale(${zoom})` }}>{nodes.length ? nodes.map((node) => <PreviewNode key={node.id} node={node}/>) : <div className="flex h-64 items-center justify-center text-sm text-slate-400">Add components to see your live preview.</div>}</div></div></section> }
