import type { LucideIcon } from 'lucide-react'
import { Activity, AlertCircle, Badge, Box, CheckSquare, CircleDot, Columns3, Dock, FormInput, GalleryVerticalEnd, Image, LayoutGrid, Menu, MousePointer2, PanelTop, PanelTopOpen, Pilcrow, Plus, Radio, Rows3, SeparatorHorizontal, Sidebar, Sparkles, Square, TextCursorInput, ToggleLeft, Type, UserRound } from 'lucide-react'
import type { CanvasNodeType } from '../../types/canvas-engine.types'

export type ComponentCategory = 'Layout' | 'Basic' | 'Forms' | 'Navigation' | 'Display' | 'Feedback' | 'Media' | 'Data Display' | 'Containers'
export interface ComponentDefinition { id: CanvasNodeType; name: string; category: ComponentCategory; icon: LucideIcon; description: string; keywords: string[]; defaultWidth: number; defaultHeight: number; defaultProperties: Record<string, unknown>; supportedChildren: CanvasNodeType[]; resizable: boolean; editable: boolean; container: boolean }
const component = (id: CanvasNodeType, name: string, category: ComponentCategory, icon: LucideIcon, width: number, height: number, properties: Record<string, unknown> = {}): ComponentDefinition => ({ id, name, category, icon, description: `${name} component`, keywords: [name.toLowerCase(), category.toLowerCase()], defaultWidth: width, defaultHeight: height, defaultProperties: properties, supportedChildren: [], resizable: true, editable: ['heading', 'text', 'button'].includes(id), container: ['container', 'card', 'section', 'grid', 'flex', 'stack'].includes(id) })
export const componentRegistry: ComponentDefinition[] = [
  component('heading','Heading','Basic',Type,240,48,{text:'Heading',level:2}), component('text','Text','Basic',Pilcrow,180,32,{text:'Text content'}), component('button','Button','Basic',MousePointer2,130,44,{text:'Button',variant:'default',size:'md',disabled:false}), component('divider','Divider','Basic',SeparatorHorizontal,240,20), component('spacer','Spacer','Layout',Plus,80,32),
  component('input','Input','Forms',FormInput,220,42,{placeholder:'Input',required:false,disabled:false}), component('textarea','Textarea','Forms',TextCursorInput,240,100,{placeholder:'Textarea'}), component('checkbox','Checkbox','Forms',CheckSquare,160,32,{label:'Checkbox',checked:false}), component('radio','Radio','Forms',CircleDot,160,32,{label:'Option'}), component('switch','Switch','Forms',ToggleLeft,160,32,{label:'Switch'}), component('select','Select','Forms',Rows3,220,42,{placeholder:'Select'}), component('button-group','Button Group','Forms',GalleryVerticalEnd,220,44),
  component('card','Card','Containers',Box,260,160), component('container','Container','Containers',Square,320,220), component('section','Section','Containers',PanelTop,480,260), component('grid','Grid','Containers',LayoutGrid,360,240), component('flex','Flex','Containers',Columns3,360,160), component('stack','Stack','Containers',Rows3,280,200),
  component('image','Image','Media',Image,220,150), component('avatar','Avatar','Media',UserRound,64,64), component('icon','Icon','Media',Sparkles,40,40), component('badge','Badge','Display',Badge,100,28), component('alert','Alert','Display',AlertCircle,300,60), component('progress','Progress','Display',Activity,240,20), component('spinner','Spinner','Display',Sparkles,40,40),
  component('navbar','Navbar','Navigation',PanelTopOpen,420,56), component('sidebar','Sidebar','Navigation',Sidebar,220,360), component('tabs','Tabs','Navigation',Dock,300,48), component('breadcrumb','Breadcrumb','Navigation',Menu,260,28), component('pagination','Pagination','Navigation',GalleryVerticalEnd,260,36), component('dialog','Dialog','Feedback',Square,360,240), component('drawer','Drawer','Feedback',Sidebar,300,360), component('tooltip','Tooltip','Feedback',AlertCircle,160,36), component('toast','Toast Placeholder','Feedback',AlertCircle,300,60)
]
export const getComponent = (id: CanvasNodeType) => componentRegistry.find((component) => component.id === id)
