import { safeStorage } from 'electron'
import Store from 'electron-store'
import { getOpenRouterApiKey } from '../config/AIEnvironment'
import type { AIProviderId, AIProviderSettings, AIRequest, AIResponse } from '../../types/ai.types'
type AIStore = { provider: AIProviderId; model: string; encryptedKey?: string }
const models: Record<AIProviderId, string[]> = { openrouter: ['openai/gpt-4o-mini'], openai: ['gpt-4o-mini'], anthropic: ['claude-3-5-haiku-latest'], gemini: ['gemini-1.5-flash'], deepseek: ['deepseek-chat'], groq: ['llama-3.1-8b-instant'] }
export class AIManager {
  private store = new Store<AIStore>({ name: 'canvascode-ai', defaults: getOpenRouterApiKey() ? { provider: 'openrouter', model: models.openrouter[0] } : { provider: 'openai', model: models.openai[0] } })
  private active = new Map<string, AbortController>()
  private apiKey() { const encrypted = this.store.get('encryptedKey'); return encrypted ? safeStorage.decryptString(Buffer.from(encrypted, 'base64')) : getOpenRouterApiKey() }
  settings(): AIProviderSettings { const value = this.store.store; const environmentKey = getOpenRouterApiKey(); const provider = environmentKey ? 'openrouter' : value.provider; const model = provider === 'openrouter' && !value.model.includes('/') ? models.openrouter[0] : value.model; return { provider, model, hasApiKey: Boolean(this.apiKey()) } }
  models(provider: AIProviderId) { return models[provider] ?? [] }
  save(provider: AIProviderId, model: string, apiKey?: string) { if (!models[provider]?.includes(model)) throw new Error('Unsupported provider or model'); if (apiKey !== undefined) { if (!safeStorage.isEncryptionAvailable()) throw new Error('Secure credential storage is unavailable'); this.store.set('encryptedKey', safeStorage.encryptString(apiKey).toString('base64')) }; this.store.set('provider', provider); this.store.set('model', model); return this.settings() }
  removeKey() { this.store.delete('encryptedKey'); return this.settings() }
  async test() { await this.request({ promptId: 'connection-test', prompt: 'Reply with OK.', timeoutMs: 15_000 }); return { success: true, ...this.settings() } }
  async request(request: AIRequest): Promise<AIResponse> { const settings = this.settings(); const apiKey = this.apiKey(); if (!apiKey) throw new Error('An API key is required'); if (settings.provider !== 'openrouter') throw new Error(`${settings.provider} is not configured for direct requests yet`); const id = crypto.randomUUID(); const controller = new AbortController(); this.active.set(id, controller); const timeout = setTimeout(() => controller.abort(), request.timeoutMs ?? 60_000); try { const response = await fetch('https://openrouter.ai/api/v1/chat/completions', { method: 'POST', signal: controller.signal, headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json', 'HTTP-Referer': 'https://canvascode.local', 'X-OpenRouter-Title': 'CanvasCode' }, body: JSON.stringify({ model: settings.model, messages: [{ role: 'user', content: request.prompt }] }) }); const payload = await response.json() as { id?: string; choices?: { message?: { content?: string } }[]; usage?: { prompt_tokens?: number; completion_tokens?: number }; error?: { message?: string } }; if (!response.ok) throw new Error(payload.error?.message ?? `OpenRouter request failed (${response.status})`); const content = payload.choices?.[0]?.message?.content; if (!content) throw new Error('OpenRouter returned an empty response'); return { id: payload.id ?? id, content, provider: settings.provider, model: settings.model, inputTokens: payload.usage?.prompt_tokens ?? Math.ceil(request.prompt.length / 4), outputTokens: payload.usage?.completion_tokens ?? Math.ceil(content.length / 4) } } catch (error) { if (controller.signal.aborted) throw new Error('AI request timed out or was cancelled'); throw error } finally { clearTimeout(timeout); this.active.delete(id) } }
  cancel(id: string) { this.active.get(id)?.abort(); return true }
}
