import { AIManager } from './AIManager'
import { getSqliteConnection } from '../db/connection'
import type { CompilationPlan } from '../../types/compilation.types'
import type { GeneratedFile, GenerationResult } from '../../types/generation.types'
import { BlueprintService } from './BlueprintService'
import { WorkspaceService } from './WorkspaceService'
export class PromptBuilderService { build(plan: CompilationPlan) { return `# CanvasCode production project generation request v1\nGenerate a complete ${plan.summary}. Return ONLY files. Every file must use this exact format: \`\`\`typescript path/to/file.ts\nfile contents\n\`\`\`. Include package.json, app/page.tsx, and all routes/controllers/services required by this plan.\nPlan: ${JSON.stringify(plan)}` } }
export class ResponseParserService { parse(value: string): GeneratedFile[] { const files: GeneratedFile[] = []; const expression = /```(?:[\w-]+)?\s+([^\n]+)\n([\s\S]*?)```/g; let match: RegExpExecArray | null; while ((match = expression.exec(value))) { const path = match[1].trim(); if (path && !path.includes('..')) files.push({ path, content: match[2], language: path.split('.').pop() ?? 'txt' }) } return files } }
export class GeneratedCodeValidator { validate(files: GeneratedFile[]) { const errors: string[] = []; const warnings: string[] = []; const paths = new Set<string>(); files.forEach((file) => { if (paths.has(file.path)) errors.push(`Duplicate file: ${file.path}`); paths.add(file.path); if (!file.content.trim()) warnings.push(`Empty file: ${file.path}`) }); if (!files.length) warnings.push('AI response contained no parseable files'); return { errors, warnings } } }
export class CodeGenerationEngine { private ai = new AIManager(); private prompts = new PromptBuilderService(); private parser = new ResponseParserService(); private validator = new GeneratedCodeValidator(); private blueprints = new BlueprintService(); private workspace = new WorkspaceService(); async generate(plan: CompilationPlan): Promise<GenerationResult> { const prompt = this.prompts.build(plan); const response = await this.ai.request({ promptId: 'code-generation-v1', prompt, context: { plan } }); const files = this.parser.parse(response.content); const validation = this.validator.validate(files); const result = { id: crypto.randomUUID(), files, ...validation, logs: ['Built versioned prompt', `Received ${response.outputTokens} output tokens`, `Parsed ${files.length} files`] }; const db = getSqliteConnection(); db.exec('CREATE TABLE IF NOT EXISTS generation_history (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, result TEXT NOT NULL, created_at INTEGER NOT NULL)'); db.prepare('INSERT INTO generation_history (id, project_id, result, created_at) VALUES (?, ?, ?, ?)').run(result.id, plan.projectId, JSON.stringify(result), Date.now()); this.workspace.writeGenerated(plan.projectId, files); this.blueprints.save(this.blueprints.build(plan.projectId, files)); return result }; load(id: string) { const row = getSqliteConnection().prepare('SELECT result FROM generation_history WHERE id = ?').get(id) as { result: string } | undefined; return row ? JSON.parse(row.result) as GenerationResult : null } }
